const ROLES = require('../../constants/roles');
const { validateWordCount } = require('./service');

function validateCreateGrievance(body, userRole) {
    const errors = [];

    if (!body.category) errors.push('Category is required');
    if (!body.sub_category) errors.push('Sub-category is required');
    if (!body.description) errors.push('Description is required');

    // Subject is required for students; for faculty it is auto-generated by the frontend
    if (userRole !== ROLES.FACULTY && !body.subject) {
        errors.push('Subject is required');
    }

    if (body.description && !validateWordCount(body.description, 100)) {
        errors.push('Description must not exceed 100 words');
    }

    const validPriorities = ['Low', 'Medium', 'High', 'Urgent'];
    if (body.priority && !validPriorities.includes(body.priority)) {
        errors.push('Invalid priority level');
    }

    if (userRole === ROLES.FACULTY) {
        const validComplaintFor = ['School', 'Residential', 'Others'];
        if (!body.complaint_for || !validComplaintFor.includes(body.complaint_for)) {
            errors.push('complaint_for is required and must be School, Residential, or Others for faculty');
        }
    }

    return errors;
}

function validateUpdateStatus(body) {
    const errors = [];
    const validStatuses = ['Open', 'In Progress', 'Resolved', 'Rejected'];

    if (!body.status || !validStatuses.includes(body.status)) {
        errors.push('Invalid or missing status');
    }
    if (!body.admin_remark || body.admin_remark.trim() === '') {
        errors.push('Admin remark is required when updating status');
    }

    return errors;
}

module.exports = {
    validateCreateGrievance,
    validateUpdateStatus
};
